(()=>{const $=id=>document.getElementById(id), progress=JSON.parse(localStorage.getItem("s3-course-progress")||"{}"), techs={}, topics={};
/* Normalize phase records into one technology per phase. */
CURRICULUM.forEach(p=>{p.technology={id:p.id,title:p.title,short:p.desc,summary:p.desc,groups:p.groups};techs[p.id]=p.technology;p.groups.forEach(g=>g.topics.forEach(t=>topics[t.id]={t,tech:p.technology,phase:p}));});
const all=()=>Object.keys(topics);
function save(){localStorage.setItem("s3-course-progress",JSON.stringify(progress));update()}
function update(){const ids=all(),done=ids.filter(x=>progress[x]).length,p=ids.length?Math.round(done/ids.length*100):0;$("pct").textContent=p+"%";$("bar").style.width=p+"%";document.querySelectorAll("[data-topic]").forEach(x=>x.classList.toggle("done",!!progress[x.dataset.topic]));document.querySelectorAll("[data-tech]").forEach(x=>{const t=techs[x.dataset.tech];const ids2=t.groups.flatMap(g=>g.topics.map(a=>a.id));x.classList.toggle("done",ids2.length&&ids2.every(i=>progress[i]))})}
function techButton(t){return `<button class="tech" data-tech="${t.id}"><strong>${t.title}</strong><small>${t.short||""}</small></button>`}
function render(){$("home").classList.add("active");$("detail").classList.remove("active");let html=`<div class="root"><b>🚀 S3 FULL-STACK DEVELOPMENT</b><small>Application-first Corporate Training</small></div><div class="v"></div><div class="phases">`;
html+=CURRICULUM.map(p=>`<section class="phase"><div class="card"><div class="num">PHASE ${p.number}</div><h3>${p.title}</h3><p>${p.description}</p><div class="nodes">${techButton(p.technology)}</div></div></section>`).join("");
html+=`</div><div class="v"></div><div class="end"><b>🏆 PRODUCTION-READY FULL-STACK ENGINEER</b><small>Learn → Build → Solve → Test → Deploy</small></div>`;$("tree").innerHTML=html;document.querySelectorAll("[data-tech]").forEach(b=>b.onclick=()=>openTech(b.dataset.tech));update()}
function openTech(id,topicId){const t=techs[id],p=CURRICULUM.find(x=>x.id===id);$("home").classList.remove("active");$("detail").classList.add("active");$("crumb").textContent=`Phase ${p.number} › ${t.title}`;$("title").textContent=t.title;$("summary").textContent=t.summary;$("detailTree").innerHTML=`<div class="mini">${techButton(t)}</div><div class="mini-v"></div><div class="groups">${t.groups.map(g=>`<section class="group"><h3>${g.title}</h3><div class="topics">${g.topics.map(x=>`<button class="topic-btn ${progress[x.id]?"done":""}" data-topic="${x.id}">${progress[x.id]?"✓ ":""}${x.title}</button>`).join("")}</div></section>`).join("")}</div>`;document.querySelector("#detailTree .mini .tech").onclick=()=>overview(t);document.querySelectorAll("#detailTree [data-topic]").forEach(b=>b.onclick=()=>showTopic(t,b.dataset.topic));topicId?showTopic(t,topicId):overview(t);scrollTo({top:0,behavior:"smooth"})}
function overview(t){$("topic").innerHTML=`<div class="head"><h2>${t.title}</h2><p>${t.summary}</p><span class="badge">Application-first learning</span></div><div class="section"><h3>📚 Topics</h3><ul>${t.groups.flatMap(g=>g.topics).map(x=>`<li><b>${x.title}</b> — ${x.description}</li>`).join("")}</ul></div><div class="section"><h3>🎯 Training Method</h3><p>Introduce the concept when the application needs it, implement it immediately, then reinforce it through practice, assignment and review.</p></div>`}
function showTopic(t,id){const x=t.groups.flatMap(g=>g.topics).find(a=>a.id===id);if(!x)return;$("topic").innerHTML=`<div class="head"><h2>${x.title}</h2><p>${x.description}</p><span class="badge">${x.level}</span></div><div class="section"><h3>💡 Application Context</h3><p>${x.example}</p></div><div class="section"><h3>💻 Practical Example</h3><pre class="code">${esc(x.example)}</pre></div><div class="section"><h3>📝 Practice</h3><p>${x.practice}</p></div><div class="section"><h3>🎤 Interview Questions</h3><ul>${x.interview.map(q=>`<li>${q}</li>`).join("")}</ul></div><div class="section"><label class="complete"><span>Mark topic completed</span><input id="done" type="checkbox" ${progress[id]?"checked":""}></label></div>`;$("done").onchange=e=>{progress[id]=e.target.checked;save();}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function search(){const q=$("search").value.trim().toLowerCase(),box=$("results");if(!q){box.classList.add("hidden");return}let r=[];Object.values(techs).forEach(t=>{if(`${t.title} ${t.summary}`.toLowerCase().includes(q))r.push({id:t.id,title:t.title,type:"Phase"});t.groups.forEach(g=>g.topics.forEach(x=>{if(`${x.title} ${x.description}`.toLowerCase().includes(q))r.push({id:t.id,topic:x.id,title:x.title,type:t.title})}))});box.classList.remove("hidden");box.innerHTML=r.slice(0,25).map(x=>`<div class="result" data-r="${x.id}" data-t="${x.topic||""}"><b>${x.title}</b><small>${x.type}</small></div>`).join("")||"<div class='result'>No result found.</div>";box.querySelectorAll("[data-r]").forEach(x=>x.onclick=()=>openTech(x.dataset.r,x.dataset.t||null))}
$("back").onclick=()=>{$("detail").classList.remove("active");$("home").classList.add("active");update();scrollTo({top:0,behavior:"smooth"})};$("search").oninput=search;$("clear").onclick=()=>{$("search").value="";search()};$("theme").onclick=()=>{const d=document.documentElement.dataset.theme==="dark";document.documentElement.dataset.theme=d?"":"dark";$("theme").textContent=d?"☾":"☀";localStorage.setItem("s3-theme",d?"light":"dark")};if(localStorage.getItem("s3-theme")==="dark"){document.documentElement.dataset.theme="dark";$("theme").textContent="☀"}render()})()
